# Backup of the previous Cloudflare-R2-enabled release workflow section.
# Source: `.github/workflows/release.yml` before R2 was disabled.
# This file is for backup/reference only and is not an active workflow.

cloudflare_r2_step:
  - name: Upload APKs to Cloudflare R2 (optional)
    if: startsWith(github.ref, 'refs/tags/v') || startsWith(github.event.inputs.tag, 'v')
    shell: bash
    env:
      R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
      R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
      R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      R2_BUCKET: ${{ vars.R2_BUCKET || secrets.R2_BUCKET }}
      R2_PREFIX: ${{ vars.R2_PREFIX }}
      R2_PUBLIC_BASE: ${{ vars.R2_PUBLIC_BASE }}
    run: |
      set -euo pipefail
      BODY_FILE="release-assets/release-body.md"
      NOTES_FILE="${RELEASE_NOTES_FILE:-}"
      if [[ -z "$NOTES_FILE" || ! -f "$NOTES_FILE" ]]; then
        NOTES_FILE="release-notes/_auto_generated.md"
        git log -1 --format='%B' > "$NOTES_FILE"
      fi
      cp "$NOTES_FILE" "$BODY_FILE"

      if [[ -z "${R2_ACCOUNT_ID:-}" || -z "${R2_ACCESS_KEY_ID:-}" || -z "${R2_SECRET_ACCESS_KEY:-}" || -z "${R2_BUCKET:-}" ]]; then
        echo "R2 not fully configured, skipping R2 upload."
        echo "RELEASE_BODY_FILE=$BODY_FILE" >> "$GITHUB_ENV"
        exit 0
      fi

      if ! command -v aws >/dev/null 2>&1; then
        echo "::warning::aws cli not found, skipping R2 upload."
        echo "RELEASE_BODY_FILE=$BODY_FILE" >> "$GITHUB_ENV"
        exit 0
      fi

      export AWS_ACCESS_KEY_ID="$R2_ACCESS_KEY_ID"
      export AWS_SECRET_ACCESS_KEY="$R2_SECRET_ACCESS_KEY"
      export AWS_DEFAULT_REGION="auto"

      ENDPOINT="https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com"
      PREFIX="${R2_PREFIX:-releases}/${RELEASE_REF}"

      aws s3 cp "release-assets/v7a.apk" "s3://${R2_BUCKET}/${PREFIX}/v7a.apk" --endpoint-url "$ENDPOINT" --only-show-errors
      aws s3 cp "release-assets/v8a.apk" "s3://${R2_BUCKET}/${PREFIX}/v8a.apk" --endpoint-url "$ENDPOINT" --only-show-errors
      aws s3 cp "release-assets/SHA256SUMS.txt" "s3://${R2_BUCKET}/${PREFIX}/SHA256SUMS.txt" --endpoint-url "$ENDPOINT" --only-show-errors

      PUBLIC_BASE="${R2_PUBLIC_BASE:-https://${R2_BUCKET}.${R2_ACCOUNT_ID}.r2.dev}"
      V7A_URL="${PUBLIC_BASE}/${PREFIX}/v7a.apk"
      V8A_URL="${PUBLIC_BASE}/${PREFIX}/v8a.apk"
      SUMS_URL="${PUBLIC_BASE}/${PREFIX}/SHA256SUMS.txt"

      {
        echo
        echo "## Mirror Download (Cloudflare R2)"
        echo "- v7a.apk: ${V7A_URL}"
        echo "- v8a.apk: ${V8A_URL}"
        echo "- SHA256SUMS.txt: ${SUMS_URL}"
      } >> "$BODY_FILE"

      echo "RELEASE_BODY_FILE=$BODY_FILE" >> "$GITHUB_ENV"
      echo "R2 upload done."

related_lines_before_disable:
  github_release_body_path: "${{ env.RELEASE_BODY_FILE || env.RELEASE_NOTES_FILE }}"
  gitee_body_file: '${RELEASE_BODY_FILE:-$RELEASE_NOTES_FILE}'
