name: Enhancement Request
description: 提交功能建议
title: "[Enhancement] "
labels:
  - enhancement
body:
  - type: textarea
    id: enhancement_details
    attributes:
      label: 需求详情
      placeholder: 请描述你的需求或建议
